import type { DatabaseClient } from '@squad/db';
import { events } from '@squad/db/schema';
import { type EventEnvelope, STREAM_NAME } from '@squad/shared-types';
import type Redis from 'ioredis';
import { v7 as uuidv7 } from 'uuid';

export type BansyncEventType = 'bansync.completed' | 'bansync.failed';

export interface BansyncCompletedPayload {
  source_id: string;
  added: number;
  updated: number;
  revoked: number;
  skipped: number;
  duration_ms: number;
  bytes: number;
}

export interface BansyncFailedPayload {
  source_id: string;
  error: string;
  consecutive_failures: number;
  duration_ms: number | null;
}

/** Builds a validated `bansync.*` envelope with a system actor, ready to persist and publish. */
export function buildBansyncEnvelope(
  type: BansyncEventType,
  payload: BansyncCompletedPayload | BansyncFailedPayload,
): EventEnvelope {
  return {
    event_id: uuidv7(),
    version: 1,
    type,
    server_id: null,
    ts: new Date().toISOString(),
    actor: { kind: 'system', id: 'ban-sync' },
    correlation_id: null,
    payload,
  };
}

/**
 * Persists a freshly built envelope to `events` and publishes it to
 * `events:global`.
 *
 * The envelope's `event_id` is generated by this worker, so no consumer-side
 * dedup applies (`processed_events` claims and Redis dedup keys belong to
 * consumers of an event, and would never conflict here). `bansync.*` events
 * are deliberately not fanned out to the `live-bus` WebSocket channel: they
 * carry source names and fetch errors meant for ban-source managers only, and
 * no live-bus consumer handles them.
 */
export async function persistAndPublish(
  db: DatabaseClient,
  redis: Pick<Redis, 'xadd'>,
  envelope: EventEnvelope,
): Promise<void> {
  await db
    .insert(events)
    .values({
      eventId: envelope.event_id,
      serverId: envelope.server_id,
      occurredAt: new Date(envelope.ts),
      kind: envelope.type,
      version: envelope.version,
      actorKind: envelope.actor?.kind ?? null,
      actorId: envelope.actor?.id ?? null,
      correlationId: envelope.correlation_id,
      payload: envelope.payload,
    })
    .onConflictDoNothing({ target: [events.eventId, events.occurredAt] });

  await redis.xadd(
    STREAM_NAME.eventsGlobal(),
    'MAXLEN',
    '~',
    '10000',
    '*',
    'envelope',
    JSON.stringify(envelope),
  );
}
