import fp from 'fastify-plugin';
import { als } from '../lib/logger.js';

export default fp(async (app) => {
  app.addHook('onRequest', (req, reply, done) => {
    // `req.id` is already validated and generated by `genReqId` in
    // server.ts (see findings #379, #1309): reuse it as the single source
    // of truth instead of deriving a second, possibly different, id here.
    const requestId = req.id;
    req.requestId = requestId;
    reply.header('x-request-id', requestId);
    als.run(
      {
        requestId,
        correlationId: requestId,
        userId: undefined,
        sessionId: undefined,
      },
      () => done(),
    );
  });
});
