packages:
  - 'apps/*'
  - 'apps/workers/*'
  - 'packages/*'
  - 'docker/rnsquadjs/plugins/*'
  - 'docker/squadjs2/plugins/*'

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@node-rs/argon2'
  - esbuild
