import type { FastifyInstance } from 'fastify';
import adminsCfgRoutes from './admins-cfg.js';
import alertRulesRoutes from './alert-rules.js';
import analyticsRoutes from './analytics.js';
import appealsRoutes from './appeals.js';
import auditRoutes from './audit.js';
import authRoutes from './auth.js';
import bssAuthRoutes from './auth-bss.js';
import discordAuthRoutes from './auth-discord.js';
import automationRulesRoutes from './automation-rules.js';
import balancerRoutes from './balancer.js';
import banSourcesRoutes from './ban-sources.js';
import bannedNamesRoutes from './banned-names.js';
import chatRoutes from './chat.js';
import clansRoutes from './clans.js';
import combatEventsRoutes from './combat-events.js';
import depotRoutes from './depot.js';
import discordInteractionsRoutes from './discord-interactions.js';
import economyRoutes from './economy.js';
import eventsRoutes from './events.js';
import externalBansRoutes from './external-bans.js';
import hostRoutes from './host.js';
import hostActionsRoutes from './host-actions.js';
import hostBackupRoutes from './host-backup.js';
import integrationsBalancerRoutes from './integrations-balancer.js';
import integrationsDiscordRoutes from './integrations-discord.js';
import integrationsDiscordRoleMappingsRoutes from './integrations-discord-role-mappings.js';
import integrationsGeoipRoutes from './integrations-geoip.js';
import integrationsVipRoutes from './integrations-vip.js';
import issuesRoutes from './issues.js';
import layersRoutes from './layers.js';
import leaderboardsRoutes from './leaderboards.js';
import leaderboardsBonusesRoutes from './leaderboards-bonuses.js';
import liveRoutes from './live.js';
import logsRoutes from './logs.js';
import markTypesRoutes from './mark-types.js';
import marksRoutes from './marks.js';
import matchesRoutes from './matches.js';
import meTokensRoutes from './me-tokens.js';
import mediaRoutes from './media.js';
import mediaLinksRoutes from './media-links.js';
import mediaPublicationsRoutes from './media-publications.js';
import mediaUploadTokensRoutes from './media-upload-tokens.js';
import messageTemplatesRoutes from './message-templates.js';
import moderationActionsRoutes from './moderation-actions.js';
import moderationBulkRoutes from './moderation-bulk.js';
import notesFeedRoutes from './notes-feed.js';
import permissionsRoutes from './permissions.js';
import playerAltCandidatesRoutes from './player-alt-candidates.js';
import playerBanAltWarningRoutes from './player-ban-alt-warning.js';
import playerCombatTrendRoutes from './player-combat-trend.js';
import playerCompareOnlineRoutes from './player-compare-online.js';
import playerCoplayRoutes from './player-coplay.js';
import playerDossierRoutes from './player-dossier.js';
import playerDossierStatsRoutes from './player-dossier-stats.js';
import playerGeoAnomaliesRoutes from './player-geo-anomalies.js';
import playerLinksRoutes from './player-links.js';
import playerMatchesRoutes from './player-matches.js';
import playerNotesRoutes from './player-notes.js';
import playerPresenceRoutes from './player-presence.js';
import playerSeedContributionRoutes from './player-seed-contribution.js';
import playerSteamFriendCheckRoutes from './player-steam-friend-check.js';
import playerSteamRefreshRoutes from './player-steam-refresh.js';
import playerRoutes from './players.js';
import publicAppealsRoutes from './public-appeals.js';
import publicBanlistRoutes from './public-banlist.js';
import publicClansRoutes from './public-clans.js';
import publicMediaRoutes from './public-media.js';
import publicStatsRoutes from './public-stats.js';
import reportActionsRoutes from './report-actions.js';
import reportAnalyticsRoutes from './report-analytics.js';
import reportsRoutes from './reports.js';
import roleAssignmentsRoutes from './role-assignments.js';
import roleMembersRoutes from './role-members.js';
import rolesRoutes from './roles.js';
import seasonsRoutes from './seasons.js';
import archiveRoutes from './server-archive.js';
import serverChatCommandsRoutes from './server-chat-commands.js';
import serverConfigRoutes from './server-configs.js';
import forceStopRoutes from './server-force-stop.js';
import serverInstallRoutes from './server-install.js';
import serverLogFilesRoutes from './server-log-files.js';
import serverLogsRoutes from './server-logs.js';
import serverMapRoutes from './server-map.js';
import serverMapVoteRoutes from './server-map-vote.js';
import serverMessagingRoutes from './server-messaging.js';
import serverMetricsRoutes from './server-metrics.js';
import serverRnsquadjsRoutes from './server-rnsquadjs.js';
import serverRosterRoutes from './server-roster.js';
import serverRotationRoutes from './server-rotation.js';
import serverRotationCalendarRoutes from './server-rotation-calendar.js';
import serverScheduledTasksRoutes from './server-scheduled-tasks.js';
import serverSeedNotificationRoutes from './server-seed-notifications.js';
import serverSeedScheduleRoutes from './server-seed-schedule.js';
import serverSeedingRoutes from './server-seeding.js';
import serverSettingsRoutes from './server-settings.js';
import serverUpdateRoutes from './server-update.js';
import serverRoutes from './servers.js';
import settingsAltDetectionRoutes from './settings-alt-detection.js';
import settingsBanlistPublicationRoutes from './settings-banlist-publication.js';
import settingsChatFlagsRoutes from './settings-chat-flags.js';
import settingsClanGuardRoutes from './settings-clan-guard.js';
import settingsCoplayRoutes from './settings-coplay.js';
import settingsEconomyRoutes from './settings-economy.js';
import setupRoutes from './setup.js';
import statisticsRoutes from './statistics.js';
import suspectsRoutes from './suspects.js';
import teamkillsRoutes from './teamkills.js';
import usersRoutes from './users.js';
import vehicleCatalogRoutes from './vehicle-catalog.js';
import vipSubscriptionRoutes from './vip-subscriptions.js';
import vipTiersRoutes from './vip-tiers.js';
import voteAnalyticsRoutes from './vote-analytics.js';
import votesRoutes from './votes.js';
import whitelistRoutes from './whitelist.js';
import whitelistApplicationsRoutes from './whitelist-applications.js';

export async function registerRoutes(app: FastifyInstance): Promise<void> {
  await app.register(authRoutes);
  await app.register(meTokensRoutes);
  await app.register(messageTemplatesRoutes);
  await app.register(hostRoutes);
  await app.register(hostActionsRoutes);
  await app.register(hostBackupRoutes);
  await app.register(serverRoutes);
  await app.register(serverRosterRoutes);
  await app.register(serverSeedingRoutes);
  await app.register(serverSeedScheduleRoutes);
  await app.register(serverScheduledTasksRoutes);
  await app.register(serverChatCommandsRoutes);
  await app.register(serverSeedNotificationRoutes);
  await app.register(serverSettingsRoutes);
  await app.register(serverUpdateRoutes);
  await app.register(archiveRoutes);
  await app.register(serverInstallRoutes);
  await app.register(serverRnsquadjsRoutes);
  await app.register(forceStopRoutes);
  await app.register(serverLogsRoutes);
  await app.register(serverLogFilesRoutes);
  await app.register(serverMapRoutes);
  await app.register(serverMapVoteRoutes);
  await app.register(serverMessagingRoutes);
  await app.register(serverMetricsRoutes);
  await app.register(serverConfigRoutes);
  await app.register(serverRotationRoutes);
  await app.register(serverRotationCalendarRoutes);
  await app.register(depotRoutes);
  await app.register(permissionsRoutes);
  await app.register(rolesRoutes);
  await app.register(roleMembersRoutes);
  await app.register(roleAssignmentsRoutes);
  await app.register(usersRoutes);
  await app.register(playerRoutes);
  await app.register(issuesRoutes);
  await app.register(marksRoutes);
  await app.register(markTypesRoutes);
  await app.register(suspectsRoutes);
  await app.register(matchesRoutes);
  await app.register(playerMatchesRoutes);
  await app.register(playerPresenceRoutes);
  await app.register(playerCompareOnlineRoutes);
  await app.register(playerSeedContributionRoutes);
  await app.register(playerSteamFriendCheckRoutes);
  await app.register(playerSteamRefreshRoutes);
  await app.register(playerCoplayRoutes);
  await app.register(playerAltCandidatesRoutes);
  await app.register(playerBanAltWarningRoutes);
  await app.register(playerLinksRoutes);
  await app.register(appealsRoutes);
  await app.register(moderationActionsRoutes);
  await app.register(moderationBulkRoutes);
  await app.register(playerDossierRoutes);
  await app.register(playerDossierStatsRoutes);
  await app.register(playerCombatTrendRoutes);
  await app.register(playerGeoAnomaliesRoutes);
  await app.register(leaderboardsRoutes);
  await app.register(leaderboardsBonusesRoutes);
  await app.register(economyRoutes);
  await app.register(mediaRoutes);
  await app.register(mediaLinksRoutes);
  await app.register(mediaPublicationsRoutes);
  await app.register(mediaUploadTokensRoutes);
  await app.register(settingsEconomyRoutes);
  await app.register(settingsChatFlagsRoutes);
  await app.register(settingsClanGuardRoutes);
  await app.register(settingsAltDetectionRoutes);
  await app.register(settingsBanlistPublicationRoutes);
  await app.register(settingsCoplayRoutes);
  await app.register(clansRoutes);
  await app.register(chatRoutes);
  await app.register(combatEventsRoutes);
  await app.register(teamkillsRoutes);
  await app.register(vehicleCatalogRoutes);
  await app.register(layersRoutes);
  await app.register(seasonsRoutes);
  await app.register(vipTiersRoutes);
  await app.register(vipSubscriptionRoutes);
  await app.register(votesRoutes);
  await app.register(voteAnalyticsRoutes);
  await app.register(reportsRoutes);
  await app.register(reportActionsRoutes);
  await app.register(reportAnalyticsRoutes);
  await app.register(eventsRoutes);
  await app.register(playerNotesRoutes);
  await app.register(notesFeedRoutes);
  await app.register(adminsCfgRoutes);
  await app.register(bannedNamesRoutes);
  await app.register(banSourcesRoutes);
  await app.register(externalBansRoutes);
  await app.register(alertRulesRoutes);
  await app.register(automationRulesRoutes);
  await app.register(balancerRoutes);
  await app.register(auditRoutes);
  await app.register(logsRoutes);
  await app.register(integrationsDiscordRoutes);
  await app.register(discordInteractionsRoutes);
  await app.register(integrationsDiscordRoleMappingsRoutes);
  await app.register(integrationsGeoipRoutes);
  await app.register(liveRoutes);
  await app.register(analyticsRoutes);
  await app.register(statisticsRoutes);
  await app.register(publicStatsRoutes);
  await app.register(publicClansRoutes);
  await app.register(publicAppealsRoutes);
  await app.register(publicMediaRoutes);
  await app.register(publicBanlistRoutes);
  await app.register(bssAuthRoutes);
  await app.register(discordAuthRoutes);
  await app.register(setupRoutes);
  await app.register(integrationsBalancerRoutes);
  await app.register(integrationsVipRoutes);
  await app.register(whitelistRoutes);
  await app.register(whitelistApplicationsRoutes);
}
