import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  customType,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';
import { servers } from './servers.js';

const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType() {
    return 'bytea';
  },
});

/**
 * Where worker-log-ingest reads `SquadGame.log` for a server the panel does
 * not host (`servers.runtime='external'`). The only kind today is `ssh`: the
 * worker opens an SSH session to the game host with the stored key and runs
 * `tail -F` on `log_path`, feeding the same parser the container tail uses.
 *
 * The private key is generated by the API, stored AES-GCM encrypted with
 * `APP_ENCRYPTION_KEY` (same blob format as the RCON password) and never
 * returned; `ssh_public_key` is the `authorized_keys` line the operator adds
 * on the game host. `host_key_fingerprint` is trust-on-first-use: NULL until
 * the worker's first successful connect, after which a different host key is
 * refused.
 */
export const serverLogSources = pgTable(
  'server_log_sources',
  {
    serverId: uuid('server_id')
      .primaryKey()
      .notNull()
      .references(() => servers.id, { onDelete: 'cascade' }),
    kind: text('kind').notNull().default('ssh'),
    sshHost: text('ssh_host').notNull(),
    sshPort: integer('ssh_port').notNull().default(22),
    sshUser: text('ssh_user').notNull(),
    sshPrivateKeyEncrypted: bytea('ssh_private_key_encrypted').notNull(),
    sshPublicKey: text('ssh_public_key').notNull(),
    hostKeyFingerprint: text('host_key_fingerprint'),
    logPath: text('log_path').notNull(),
    enabled: boolean('enabled').notNull().default(true),
    keyVersion: integer('key_version').notNull().default(1),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'date' }).defaultNow().notNull(),
  },
  (table) => ({
    kindCheck: check('server_log_sources_kind_chk', sql`${table.kind} IN ('ssh')`),
  }),
);

export type ServerLogSourceRow = typeof serverLogSources.$inferSelect;
export type NewServerLogSource = typeof serverLogSources.$inferInsert;
